export const ROUTES = {
  HOME: "/",
  APPLY: "/apply",
  LOGIN: "/auth/login",
  SIGNUP: "/auth/signup",
  REGISTER: "/auth/register",
  PREPARER: "/preparer",
  PORTAL: "/portal",
  PORTAL_CHECKLIST: "/portal/checklist",
  PORTAL_DOCUMENTS: "/portal/documents",
  PORTAL_NOTIFICATIONS: "/portal/notifications",
  PORTAL_TASKS: "/portal/tasks",
  PORTAL_SIGNALS: "/portal/signals",
  ADMIN: "/admin",
  ADMIN_CLIENTS: "/admin/clients",
  ADMIN_CLIENT_NEW: "/admin/clients/new",
} as const;
